- hosts: all
  become: true
  vars:
    wp_version: 5.7.1
    wp_webserver: nginx
    wp_mysql_db: "wordpress"
    wp_mysql_user: "datascientest"
    wp_mysql_password: "mysql_pass"
    wp_mysql_host: "172.31.36.186" 
    wp_admin_email: "admin@datascientest.fr"
    wp_sitename: "demo.com"
    wp_install_dir: "/var/www/demo.com"
  roles:
    - role: mysql
      when: "'mysql_servers' in group_names"

    - role: wordpress
      when: "'wordpress_servers' in group_names"
